name: alinemol

channels:
  - conda-forge
  - defaults

dependencies:
  - python >3.8
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - statsmodels
  - networkx
  - tqdm
  - pytorch >= 1.13
  - dgl
  - dgllife
  - pytorch_geometric
  - pyyaml
  - typing-extensions

  # Chemistry
  - datamol
  - molfeat
  - splito

  # Doc
  - mkdocs
  - mkdocs-material >=7.1.1
  - mkdocs-material-extensions
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-jupyter
  - markdown-include
  - mdx_truly_sane_lists
  - nbconvert
  - mike >=1.0.0

  # Dev
  - pytest >=6.0
  - pytest-dotenv
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
  - black >=22
  - ruff
  - jupyterlab
  - nbconvert  


  - pip:
    - chembl-webresource-client
    - rdkit
    - biopython
    - astartes
    - datasail
    - umap-learn
    - loguru
